# coding: utf-8

"""
    divar_interface/open_platform/chatapi/chatapi.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kenar_api_client.models.payment_ticket_validate_request import PaymentTicketValidateRequest

class TestPaymentTicketValidateRequest(unittest.TestCase):
    """PaymentTicketValidateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentTicketValidateRequest:
        """Test PaymentTicketValidateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentTicketValidateRequest`
        """
        model = PaymentTicketValidateRequest()
        if include_optional:
            return PaymentTicketValidateRequest(
                ticket_uuid = '',
                phone_number = '',
                user_id = '',
                service_cost = 56
            )
        else:
            return PaymentTicketValidateRequest(
        )
        """

    def testPaymentTicketValidateRequest(self):
        """Test PaymentTicketValidateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
