# coding: utf-8

"""
    Kenar API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kenar_api_client.models.darvaze_get_car_ownership_status_response import DarvazeGetCarOwnershipStatusResponse

class TestDarvazeGetCarOwnershipStatusResponse(unittest.TestCase):
    """DarvazeGetCarOwnershipStatusResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DarvazeGetCarOwnershipStatusResponse:
        """Test DarvazeGetCarOwnershipStatusResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DarvazeGetCarOwnershipStatusResponse`
        """
        model = DarvazeGetCarOwnershipStatusResponse()
        if include_optional:
            return DarvazeGetCarOwnershipStatusResponse(
                description = '',
                status = 'PENDING'
            )
        else:
            return DarvazeGetCarOwnershipStatusResponse(
        )
        """

    def testDarvazeGetCarOwnershipStatusResponse(self):
        """Test DarvazeGetCarOwnershipStatusResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
