# coding: utf-8

"""
    API کنار

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kenar_api_client.models.get_upload_urls_v2_response_upload_format import GetUploadURLsV2ResponseUploadFormat

class TestGetUploadURLsV2ResponseUploadFormat(unittest.TestCase):
    """GetUploadURLsV2ResponseUploadFormat unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetUploadURLsV2ResponseUploadFormat:
        """Test GetUploadURLsV2ResponseUploadFormat
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetUploadURLsV2ResponseUploadFormat`
        """
        model = GetUploadURLsV2ResponseUploadFormat()
        if include_optional:
            return GetUploadURLsV2ResponseUploadFormat(
                http_method = 'GET',
                url = ''
            )
        else:
            return GetUploadURLsV2ResponseUploadFormat(
        )
        """

    def testGetUploadURLsV2ResponseUploadFormat(self):
        """Test GetUploadURLsV2ResponseUploadFormat"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
