# coding: utf-8

"""
    Kenar API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kenar_api_client.models.post_temporary_residence_fields import PostTemporaryResidenceFields

class TestPostTemporaryResidenceFields(unittest.TestCase):
    """PostTemporaryResidenceFields unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostTemporaryResidenceFields:
        """Test PostTemporaryResidenceFields
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostTemporaryResidenceFields`
        """
        model = PostTemporaryResidenceFields()
        if include_optional:
            return PostTemporaryResidenceFields(
                area = 100,
                check_in_time = '08:00',
                check_out_time = '20:00',
                comfort_amenities = ["COMFORT_AMENITY_TV","COMFORT_AMENITY_WASHING_MACHINE","COMFORT_AMENITY_AIR_CONDITIONER"],
                damage_deposit = '2000000',
                extra_person_capacity = 2,
                fully_furnished = True,
                has_own_image = True,
                heating_cooling_system = ["HEATING_COOLING_SYSTEM_SPLIT","HEATING_COOLING_SYSTEM_RADIATOR"],
                house_rules = 'no smoking',
                minimum_stay = 3,
                pets_allowed = 'PETS_ALLOWED_YES',
                price_cost_per_extra_person = '150000',
                price_regular_days = '1000000',
                price_special_days = '1500000',
                price_weekends = '1200000',
                regular_person_capacity = 4,
                rental_period = 'RENTAL_PERIOD_DAILY',
                rooms_count = 'ROOMS_COUNT_2'
            )
        else:
            return PostTemporaryResidenceFields(
        )
        """

    def testPostTemporaryResidenceFields(self):
        """Test PostTemporaryResidenceFields"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
