# coding: utf-8

"""
    Kenar API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kenar_api_client.api.events_api import EventsApi


class TestEventsApi(unittest.TestCase):
    """EventsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EventsApi()

    def tearDown(self) -> None:
        pass

    def test_events_register_event_subscription(self) -> None:
        """Test case for events_register_event_subscription

        اشتراک در رویداد
        """
        pass

    def test_events_send_event(self) -> None:
        """Test case for events_send_event

        Send an event to a user
        """
        pass


if __name__ == '__main__':
    unittest.main()
