# coding: utf-8

"""
    API کنار

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kenar_api_client.models.home_presell_fields_delivery_year import HomePresellFieldsDeliveryYear

class TestHomePresellFieldsDeliveryYear(unittest.TestCase):
    """HomePresellFieldsDeliveryYear unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHomePresellFieldsDeliveryYear(self):
        """Test HomePresellFieldsDeliveryYear"""
        # inst = HomePresellFieldsDeliveryYear()

if __name__ == '__main__':
    unittest.main()
