# coding: utf-8

"""
    Kenar API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kenar_api_client.api.semantic_api import SemanticApi


class TestSemanticApi(unittest.TestCase):
    """SemanticApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SemanticApi()

    def tearDown(self) -> None:
        pass

    def test_semantic_create_post_semantic(self) -> None:
        """Test case for semantic_create_post_semantic

        Create Post Semantic
        """
        pass

    def test_semantic_create_user_semantic(self) -> None:
        """Test case for semantic_create_user_semantic

        Create User Semantic
        """
        pass

    def test_semantic_create_user_semantic2(self) -> None:
        """Test case for semantic_create_user_semantic2

        Create User Semantic
        """
        pass

    def test_semantic_delete_user_semantic(self) -> None:
        """Test case for semantic_delete_user_semantic

        Delete User Semantic
        """
        pass

    def test_semantic_delete_user_semantic2(self) -> None:
        """Test case for semantic_delete_user_semantic2

        Delete User Semantic
        """
        pass


if __name__ == '__main__':
    unittest.main()
