# coding: utf-8

"""
    divar_interface/open_platform/chatapi/chatapi.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kenar_api_client.models.o_auth_scope_scope import OAuthScopeScope

class TestOAuthScopeScope(unittest.TestCase):
    """OAuthScopeScope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOAuthScopeScope(self):
        """Test OAuthScopeScope"""
        # inst = OAuthScopeScope()

if __name__ == '__main__':
    unittest.main()
