# coding: utf-8

"""
    API کنار

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kenar_api_client.api.payment_api import PaymentApi


class TestPaymentApi(unittest.TestCase):
    """PaymentApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PaymentApi()

    def tearDown(self) -> None:
        pass

    def test_payment_commit_wallet_transaction(self) -> None:
        """Test case for payment_commit_wallet_transaction

        نهایی کردن تراکنش کیف پول
        """
        pass

    def test_payment_create_wallet_payment(self) -> None:
        """Test case for payment_create_wallet_payment

        ایجاد پرداخت کیف پول
        """
        pass

    def test_payment_get_balance(self) -> None:
        """Test case for payment_get_balance

        دریافت موجودی اپلیکیشن
        """
        pass

    def test_payment_get_post_pricing(self) -> None:
        """Test case for payment_get_post_pricing

        دریافت قیمت خدمات آگهی
        """
        pass

    def test_payment_get_transaction(self) -> None:
        """Test case for payment_get_transaction

        دریافت جزئیات تراکنش
        """
        pass

    def test_payment_list_transactions(self) -> None:
        """Test case for payment_list_transactions

        لیست تراکنش‌ها
        """
        pass

    def test_payment_publish_user_post(self) -> None:
        """Test case for payment_publish_user_post

        انتشار آگهی کاربر (پرداخت توسط ارائه‌دهنده)
        """
        pass

    def test_payment_renew_post(self) -> None:
        """Test case for payment_renew_post

        تمدید آگهی
        """
        pass

    def test_payment_reorder_post(self) -> None:
        """Test case for payment_reorder_post

        نردبان آگهی
        """
        pass

    def test_payment_retrieve_wallet_transaction(self) -> None:
        """Test case for payment_retrieve_wallet_transaction

        دریافت تراکنش کیف پول
        """
        pass

    def test_payment_submit_user_payment(self) -> None:
        """Test case for payment_submit_user_payment

        ثبت رکورد پرداخت کاربر
        """
        pass


if __name__ == '__main__':
    unittest.main()
