# coding: utf-8

"""
    API کنار

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kenar_api_client.models.post_submit_post_request import PostSubmitPostRequest

class TestPostSubmitPostRequest(unittest.TestCase):
    """PostSubmitPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostSubmitPostRequest:
        """Test PostSubmitPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostSubmitPostRequest`
        """
        model = PostSubmitPostRequest()
        if include_optional:
            return PostSubmitPostRequest(
                apartment_sell = kenar_api_client.models.post_apartment_sell_fields.postApartmentSellFields(
                    floor = 1, 
                    has_elevator = True, 
                    has_own_image = True, 
                    has_parking = True, 
                    has_warehouse = True, 
                    price = '1000000000', 
                    rooms_count = 'ROOMS_COUNT_2', 
                    size = 100, 
                    year_built = 1404, ),
                chat_enabled = True,
                city = 'tehran',
                description = 'I'm available only in chat.',
                district = 'abshar',
                hide_phone = True,
                home_presell = kenar_api_client.models.post_home_presell_fields.postHomePresellFields(
                    base_price_per_square_meter = '50000000', 
                    construction_phase = 'CONSTRUCTION_PHASE_EXCAVATION', 
                    delivery_month = 'DELIVERY_MONTH_TIR', 
                    delivery_payment_percentage = 60, 
                    delivery_year = 'DELIVERY_YEAR_1405', 
                    developer_company_name = 'Mehr Construction Group', 
                    down_payment_percentage = 40, 
                    has_own_image = True, 
                    min_unit_size = 60, 
                    project_name = 'Paradise Tower', 
                    project_physical_progress_percentage = 10, 
                    unit_types_offered = ["UNIT_TYPE_RESIDENTIAL_APARTMENT","UNIT_TYPE_COMMERCIAL_UNIT"], ),
                images = [
                    ''
                    ],
                landline_numbers = ["02188888888","02188888889"],
                latitude = 35.7152,
                location_type = 'LOCATION_TYPE_EXACT',
                longitude = 51.4043,
                services = kenar_api_client.models.open_platformpost_services_fields.open_platformpostServicesFields(
                    category = 'CATEGORY_CAR_AND_MOTOR', 
                    expertise_ids = ["1","2"], 
                    work_hours_end = 18, 
                    work_hours_start = 9, 
                    work_on_holidays = True, 
                    works_24_7 = False, ),
                temporary_residence = kenar_api_client.models.post_temporary_residence_fields.postTemporaryResidenceFields(
                    area = 100, 
                    check_in_time = '08:00', 
                    check_out_time = '20:00', 
                    comfort_amenities = ["COMFORT_AMENITY_TV","COMFORT_AMENITY_WASHING_MACHINE","COMFORT_AMENITY_AIR_CONDITIONER"], 
                    damage_deposit = '2000000', 
                    extra_person_capacity = 2, 
                    fully_furnished = True, 
                    has_own_image = True, 
                    heating_cooling_system = ["HEATING_COOLING_SYSTEM_SPLIT","HEATING_COOLING_SYSTEM_RADIATOR"], 
                    house_rules = 'no smoking', 
                    minimum_stay = 3, 
                    pets_allowed = 'PETS_ALLOWED_YES', 
                    price_cost_per_extra_person = '150000', 
                    price_regular_days = '1000000', 
                    price_special_days = '1500000', 
                    price_weekends = '1200000', 
                    regular_person_capacity = 4, 
                    rental_period = 'RENTAL_PERIOD_DAILY', 
                    rooms_count = 'ROOMS_COUNT_2', ),
                title = 'Temporary Residence for Rent in Tehran'
            )
        else:
            return PostSubmitPostRequest(
                chat_enabled = True,
                city = 'tehran',
                description = 'I'm available only in chat.',
                hide_phone = True,
                images = [
                    ''
                    ],
                location_type = 'LOCATION_TYPE_EXACT',
                title = 'Temporary Residence for Rent in Tehran',
        )
        """

    def testPostSubmitPostRequest(self):
        """Test PostSubmitPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
