# coding: utf-8

"""
    divar_interface/open_platform/chatapi/chatapi.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kenar_api_client.api.chat_api_api import ChatAPIApi


class TestChatAPIApi(unittest.TestCase):
    """ChatAPIApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ChatAPIApi()

    def tearDown(self) -> None:
        pass

    def test_chat_api_chat_bot_send_message(self) -> None:
        """Test case for chat_api_chat_bot_send_message

        Send a message to a ChatBot conversation
        """
        pass

    def test_chat_api_chat_bot_send_message2(self) -> None:
        """Test case for chat_api_chat_bot_send_message2

        Send a message to a ChatBot conversation
        """
        pass

    def test_chat_api_chat_bot_send_message3(self) -> None:
        """Test case for chat_api_chat_bot_send_message3

        Send a message to a ChatBot conversation
        """
        pass

    def test_chat_api_conversation_send_message(self) -> None:
        """Test case for chat_api_conversation_send_message

        Send a message to a conversation
        """
        pass

    def test_chat_api_generate_upload_token(self) -> None:
        """Test case for chat_api_generate_upload_token

        Generate an upload token
        """
        pass

    def test_chat_api_get_conversation(self) -> None:
        """Test case for chat_api_get_conversation

        Get Conversation by it's ID
        """
        pass


if __name__ == '__main__':
    unittest.main()
