# coding: utf-8

"""
    Kenar API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kenar_api_client.api.assets_api import AssetsApi


class TestAssetsApi(unittest.TestCase):
    """AssetsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AssetsApi()

    def tearDown(self) -> None:
        pass

    def test_assets_get_body_statuses(self) -> None:
        """Test case for assets_get_body_statuses

        Get available body-status options in Divar vehicle categories
        """
        pass

    def test_assets_get_brand_models(self) -> None:
        """Test case for assets_get_brand_models

        Get brand models in a Divar category
        """
        pass

    def test_assets_get_categories(self) -> None:
        """Test case for assets_get_categories

        Get Divar categories
        """
        pass

    def test_assets_get_cities(self) -> None:
        """Test case for assets_get_cities

        Get Divar cities
        """
        pass

    def test_assets_get_colors(self) -> None:
        """Test case for assets_get_colors

        Get colors in a Divar category
        """
        pass

    def test_assets_get_districts(self) -> None:
        """Test case for assets_get_districts

        Get Divar districts
        """
        pass

    def test_assets_get_districts2(self) -> None:
        """Test case for assets_get_districts2

        Get Divar districts
        """
        pass

    def test_assets_get_internal_storages(self) -> None:
        """Test case for assets_get_internal_storages

        Get available internal-storage options in Divar mobile/tablet/laptop categories
        """
        pass

    def test_assets_get_o_auth_scopes(self) -> None:
        """Test case for assets_get_o_auth_scopes

        Get KenarDivar OAuth scopes
        """
        pass

    def test_assets_get_permissions(self) -> None:
        """Test case for assets_get_permissions

        Get KenarDivar permissions
        """
        pass

    def test_assets_get_ram_memories(self) -> None:
        """Test case for assets_get_ram_memories

        Get available ram-memory options in Divar mobile/tablet/laptop categories
        """
        pass

    def test_assets_get_service_types(self) -> None:
        """Test case for assets_get_service_types

        Get available service types in KenarDivar
        """
        pass


if __name__ == '__main__':
    unittest.main()
