# coding: utf-8

"""
    Kenar API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kenar_api_client.models.message_video_data import MessageVideoData

class TestMessageVideoData(unittest.TestCase):
    """MessageVideoData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MessageVideoData:
        """Test MessageVideoData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MessageVideoData`
        """
        model = MessageVideoData()
        if include_optional:
            return MessageVideoData(
                link = '',
                size_bytes = '',
                thumbnail_link = ''
            )
        else:
            return MessageVideoData(
        )
        """

    def testMessageVideoData(self):
        """Test MessageVideoData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
