# coding: utf-8

"""
    API کنار

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kenar_api_client.models.post_customized_button_type import PostCustomizedButtonType

class TestPostCustomizedButtonType(unittest.TestCase):
    """PostCustomizedButtonType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostCustomizedButtonType(self):
        """Test PostCustomizedButtonType"""
        # inst = PostCustomizedButtonType()

if __name__ == '__main__':
    unittest.main()
