# coding: utf-8

"""
    divar_interface/open_platform/chatapi/chatapi.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kenar_api_client.models.message_image_data import MessageImageData

class TestMessageImageData(unittest.TestCase):
    """MessageImageData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MessageImageData:
        """Test MessageImageData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MessageImageData`
        """
        model = MessageImageData()
        if include_optional:
            return MessageImageData(
                link = '',
                size_bytes = '',
                height_px = 56,
                width_px = 56
            )
        else:
            return MessageImageData(
        )
        """

    def testMessageImageData(self):
        """Test MessageImageData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
