# coding: utf-8

"""
    Kenar API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kenar_api_client.models.payment_list_transactions_response import PaymentListTransactionsResponse

class TestPaymentListTransactionsResponse(unittest.TestCase):
    """PaymentListTransactionsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentListTransactionsResponse:
        """Test PaymentListTransactionsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentListTransactionsResponse`
        """
        model = PaymentListTransactionsResponse()
        if include_optional:
            return PaymentListTransactionsResponse(
                next_page_token = '',
                transactions = [
                    kenar_api_client.models.payment_transaction.paymentTransaction(
                        cost_rials = '', 
                        extra_details = '', 
                        id = '', 
                        state = 'TRANSACTION_STATE_PENDING', 
                        type = 'TRANSACTION_TYPE_REORDER', )
                    ]
            )
        else:
            return PaymentListTransactionsResponse(
        )
        """

    def testPaymentListTransactionsResponse(self):
        """Test PaymentListTransactionsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
