# coding: utf-8

"""
    Kenar API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kenar_api_client.models.semantic_user_semantic_deleted import SemanticUserSemanticDeleted

class TestSemanticUserSemanticDeleted(unittest.TestCase):
    """SemanticUserSemanticDeleted unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SemanticUserSemanticDeleted:
        """Test SemanticUserSemanticDeleted
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SemanticUserSemanticDeleted`
        """
        model = SemanticUserSemanticDeleted()
        if include_optional:
            return SemanticUserSemanticDeleted(
                app_slug = '',
                id = '',
                phone = ''
            )
        else:
            return SemanticUserSemanticDeleted(
        )
        """

    def testSemanticUserSemanticDeleted(self):
        """Test SemanticUserSemanticDeleted"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
