# coding: utf-8

"""
    Kenar API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kenar_api_client.models.widgets_action import WidgetsAction

class TestWidgetsAction(unittest.TestCase):
    """WidgetsAction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WidgetsAction:
        """Test WidgetsAction
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WidgetsAction`
        """
        model = WidgetsAction()
        if include_optional:
            return WidgetsAction(
                page_pop_link = True,
                payload = {
                    'key' : null
                    },
                type = 'MAP_PREVIEW'
            )
        else:
            return WidgetsAction(
        )
        """

    def testWidgetsAction(self):
        """Test WidgetsAction"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
