# coding: utf-8

"""
    Kenar API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kenar_api_client.models.addons_addon_secondary_linkage import AddonsAddonSecondaryLinkage

class TestAddonsAddonSecondaryLinkage(unittest.TestCase):
    """AddonsAddonSecondaryLinkage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddonsAddonSecondaryLinkage:
        """Test AddonsAddonSecondaryLinkage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddonsAddonSecondaryLinkage`
        """
        model = AddonsAddonSecondaryLinkage()
        if include_optional:
            return AddonsAddonSecondaryLinkage(
                position = 'POST_SPEC_HEAD',
                widgets = None
            )
        else:
            return AddonsAddonSecondaryLinkage(
        )
        """

    def testAddonsAddonSecondaryLinkage(self):
        """Test AddonsAddonSecondaryLinkage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
