# coding: utf-8

"""
    API کنار

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kenar_api_client.models.post_get_image_upload_url_response import PostGetImageUploadURLResponse

class TestPostGetImageUploadURLResponse(unittest.TestCase):
    """PostGetImageUploadURLResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostGetImageUploadURLResponse:
        """Test PostGetImageUploadURLResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostGetImageUploadURLResponse`
        """
        model = PostGetImageUploadURLResponse()
        if include_optional:
            return PostGetImageUploadURLResponse(
                upload_url = ''
            )
        else:
            return PostGetImageUploadURLResponse(
        )
        """

    def testPostGetImageUploadURLResponse(self):
        """Test PostGetImageUploadURLResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
