# coding: utf-8

"""
    Kenar API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kenar_api_client.models.addons_addon_linkage import AddonsAddonLinkage

class TestAddonsAddonLinkage(unittest.TestCase):
    """AddonsAddonLinkage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddonsAddonLinkage(self):
        """Test AddonsAddonLinkage"""
        # inst = AddonsAddonLinkage()

if __name__ == '__main__':
    unittest.main()
