# coding: utf-8

"""
    API کنار

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kenar_api_client.api.post_api import PostApi


class TestPostApi(unittest.TestCase):
    """PostApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PostApi()

    def tearDown(self) -> None:
        pass

    def test_post_can_user_submit_post(self) -> None:
        """Test case for post_can_user_submit_post

        بررسی اینکه آیا کاربر می‌تواند آگهی ارسال کند
        """
        pass

    def test_post_create_business_customized_button(self) -> None:
        """Test case for post_create_business_customized_button

        ایجاد دکمه اختصاصی برای آگهی‌های کسب‌و‌کار
        """
        pass

    def test_post_delete_business_customized_button(self) -> None:
        """Test case for post_delete_business_customized_button

        حذف دکمه اختصاصی از آگهی‌های کسب‌و‌کار
        """
        pass

    def test_post_delete_post_customized_button(self) -> None:
        """Test case for post_delete_post_customized_button

        حذف دکمه اختصاصی از آگهی
        """
        pass

    def test_post_delete_user_post(self) -> None:
        """Test case for post_delete_user_post

        حذف آگهی
        """
        pass

    def test_post_edit_post(self) -> None:
        """Test case for post_edit_post

        ویرایش آگهی
        """
        pass

    def test_post_edit_post_v2(self) -> None:
        """Test case for post_edit_post_v2

        ویرایش آگهی با پشتیبانی از فیلد ماسک
        """
        pass

    def test_post_get_image_upload_url(self) -> None:
        """Test case for post_get_image_upload_url

        دریافت آدرس اپلود تصاویر آگهی (منسوخ شده)
        """
        pass

    def test_post_get_post_stats(self) -> None:
        """Test case for post_get_post_stats

        دریافت آمارهای آگهی
        """
        pass

    def test_post_get_upload_urls_v2(self) -> None:
        """Test case for post_get_upload_urls_v2

        دریافت آدرس آپلود برای تصاویر و ویدیو‌ی آگهی‌ها
        """
        pass

    def test_post_get_user_post(self) -> None:
        """Test case for post_get_user_post

        دریافت آگهی با توکن
        """
        pass

    def test_post_set_post_customized_button(self) -> None:
        """Test case for post_set_post_customized_button

        تنظیم دکمه اختصاصی بر روی آگهی ثبت شده
        """
        pass

    def test_post_submit_post(self) -> None:
        """Test case for post_submit_post

        ثبت آگهی
        """
        pass

    def test_post_submit_post_v2(self) -> None:
        """Test case for post_submit_post_v2

        ثبت آگهی با استفاده از اعتبارسنجی قالب JSON
        """
        pass

    def test_post_submit_user_post(self) -> None:
        """Test case for post_submit_user_post

        ثبت آگهی به عنوان کاربر
        """
        pass


if __name__ == '__main__':
    unittest.main()
