# coding: utf-8

"""
    divar_interface/open_platform/chatapi/chatapi.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kenar_api_client.models.semantic_create_post_semantic_body import SemanticCreatePostSemanticBody

class TestSemanticCreatePostSemanticBody(unittest.TestCase):
    """SemanticCreatePostSemanticBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SemanticCreatePostSemanticBody:
        """Test SemanticCreatePostSemanticBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SemanticCreatePostSemanticBody`
        """
        model = SemanticCreatePostSemanticBody()
        if include_optional:
            return SemanticCreatePostSemanticBody(
                semantic = {
                    'key' : ''
                    },
                ticket_uuid = '',
                cost = 56
            )
        else:
            return SemanticCreatePostSemanticBody(
        )
        """

    def testSemanticCreatePostSemanticBody(self):
        """Test SemanticCreatePostSemanticBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
