# coding: utf-8

"""
    divar_interface/open_platform/chatapi/chatapi.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kenar_api_client.models.finder_get_user_posts_response_post import FinderGetUserPostsResponsePost

class TestFinderGetUserPostsResponsePost(unittest.TestCase):
    """FinderGetUserPostsResponsePost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FinderGetUserPostsResponsePost:
        """Test FinderGetUserPostsResponsePost
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FinderGetUserPostsResponsePost`
        """
        model = FinderGetUserPostsResponsePost()
        if include_optional:
            return FinderGetUserPostsResponsePost(
                token = '',
                title = '',
                images = [
                    ''
                    ],
                category = ''
            )
        else:
            return FinderGetUserPostsResponsePost(
        )
        """

    def testFinderGetUserPostsResponsePost(self):
        """Test FinderGetUserPostsResponsePost"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
