# coding: utf-8

"""
    Kenar API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kenar_api_client.models.darvaze_verify_post_code_validation_response_status import DarvazeVerifyPostCodeValidationResponseStatus

class TestDarvazeVerifyPostCodeValidationResponseStatus(unittest.TestCase):
    """DarvazeVerifyPostCodeValidationResponseStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDarvazeVerifyPostCodeValidationResponseStatus(self):
        """Test DarvazeVerifyPostCodeValidationResponseStatus"""
        # inst = DarvazeVerifyPostCodeValidationResponseStatus()

if __name__ == '__main__':
    unittest.main()
