# coding: utf-8

"""
    API کنار

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kenar_api_client.models.post_general_data_post_video import PostGeneralDataPostVideo

class TestPostGeneralDataPostVideo(unittest.TestCase):
    """PostGeneralDataPostVideo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostGeneralDataPostVideo:
        """Test PostGeneralDataPostVideo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostGeneralDataPostVideo`
        """
        model = PostGeneralDataPostVideo()
        if include_optional:
            return PostGeneralDataPostVideo(
                duration = '34',
                name = 'raw/4786eb10-eac6-4077-b622-78c1c42855c7.mp4',
                thumbnail_name = 'thumbnail/4786eb10-eac6-4077-b622-78c1c42855c7.jpg'
            )
        else:
            return PostGeneralDataPostVideo(
                duration = '34',
                name = 'raw/4786eb10-eac6-4077-b622-78c1c42855c7.mp4',
                thumbnail_name = 'thumbnail/4786eb10-eac6-4077-b622-78c1c42855c7.jpg',
        )
        """

    def testPostGeneralDataPostVideo(self):
        """Test PostGeneralDataPostVideo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
