# coding: utf-8

"""
    Kenar API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kenar_api_client.models.finder_get_post_response import FinderGetPostResponse

class TestFinderGetPostResponse(unittest.TestCase):
    """FinderGetPostResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FinderGetPostResponse:
        """Test FinderGetPostResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FinderGetPostResponse`
        """
        model = FinderGetPostResponse()
        if include_optional:
            return FinderGetPostResponse(
                business_data = kenar_api_client.models.get_post_response_business_data.GetPostResponseBusinessData(
                    business_name = '', 
                    business_type = 'CAR', ),
                category = '',
                chat_enabled = True,
                city = '',
                data = None,
                district = '',
                first_published_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                is_phone_hidden = True,
                state = 'PUBLISHED',
                supplier_chat_assistant_enabled = True,
                token = ''
            )
        else:
            return FinderGetPostResponse(
        )
        """

    def testFinderGetPostResponse(self):
        """Test FinderGetPostResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
