# coding: utf-8

"""
    divar_interface/open_platform/chatapi/chatapi.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kenar_api_client.api.payment_ticket_api import PaymentTicketApi


class TestPaymentTicketApi(unittest.TestCase):
    """PaymentTicketApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PaymentTicketApi()

    def tearDown(self) -> None:
        pass

    def test_payment_ticket_validate(self) -> None:
        """Test case for payment_ticket_validate

        Validate a payment ticket
        """
        pass


if __name__ == '__main__':
    unittest.main()
