# coding: utf-8

"""
    API کنار

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kenar_api_client.models.chatapi_message_sender_side import ChatapiMessageSenderSide

class TestChatapiMessageSenderSide(unittest.TestCase):
    """ChatapiMessageSenderSide unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChatapiMessageSenderSide(self):
        """Test ChatapiMessageSenderSide"""
        # inst = ChatapiMessageSenderSide()

if __name__ == '__main__':
    unittest.main()
