# coding: utf-8

"""
    Kenar API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kenar_api_client.models.post_location_type import PostLocationType

class TestPostLocationType(unittest.TestCase):
    """PostLocationType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostLocationType(self):
        """Test PostLocationType"""
        # inst = PostLocationType()

if __name__ == '__main__':
    unittest.main()
