# coding: utf-8

"""
    divar_interface/open_platform/chatapi/chatapi.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kenar_api_client.models.premium_panel_business_data_sub_business_type import PremiumPanelBusinessDataSubBusinessType

class TestPremiumPanelBusinessDataSubBusinessType(unittest.TestCase):
    """PremiumPanelBusinessDataSubBusinessType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPremiumPanelBusinessDataSubBusinessType(self):
        """Test PremiumPanelBusinessDataSubBusinessType"""
        # inst = PremiumPanelBusinessDataSubBusinessType()

if __name__ == '__main__':
    unittest.main()
