# coding: utf-8

"""
    Kenar API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kenar_api_client.models.addons_selector_row import AddonsSelectorRow

class TestAddonsSelectorRow(unittest.TestCase):
    """AddonsSelectorRow unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddonsSelectorRow:
        """Test AddonsSelectorRow
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddonsSelectorRow`
        """
        model = AddonsSelectorRow()
        if include_optional:
            return AddonsSelectorRow(
                action = kenar_api_client.models.action.Action(
                    get_dynamic_action = kenar_api_client.models.get_dynamic_action.Get Dynamic Action(
                        data = {"your-internal-id":"something"}, ), 
                    open_direct_link = 'https://your-site.com/some-path', 
                    open_server_link = kenar_api_client.models.open_server_link.Open Server Link(
                        data = {"your-internal-id":"something"}, ), ),
                has_divider = True,
                icon_name = 'KEYBOARD_ARROW_RIGHT',
                image_id = '',
                title = ''
            )
        else:
            return AddonsSelectorRow(
        )
        """

    def testAddonsSelectorRow(self):
        """Test AddonsSelectorRow"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
