# coding: utf-8

"""
    API کنار

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kenar_api_client.models.post_apartment_sell_fields import PostApartmentSellFields

class TestPostApartmentSellFields(unittest.TestCase):
    """PostApartmentSellFields unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostApartmentSellFields:
        """Test PostApartmentSellFields
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostApartmentSellFields`
        """
        model = PostApartmentSellFields()
        if include_optional:
            return PostApartmentSellFields(
                floor = 1,
                has_elevator = True,
                has_own_image = True,
                has_parking = True,
                has_warehouse = True,
                price = '1000000000',
                rooms_count = 'ROOMS_COUNT_2',
                size = 100,
                year_built = 1404
            )
        else:
            return PostApartmentSellFields(
                floor = 1,
                has_elevator = True,
                has_own_image = True,
                has_parking = True,
                has_warehouse = True,
                price = '1000000000',
                rooms_count = 'ROOMS_COUNT_2',
                size = 100,
                year_built = 1404,
        )
        """

    def testPostApartmentSellFields(self):
        """Test PostApartmentSellFields"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
