# coding: utf-8

"""
    API کنار

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kenar_api_client.models.assets_get_body_statuses_response import AssetsGetBodyStatusesResponse

class TestAssetsGetBodyStatusesResponse(unittest.TestCase):
    """AssetsGetBodyStatusesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AssetsGetBodyStatusesResponse:
        """Test AssetsGetBodyStatusesResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AssetsGetBodyStatusesResponse`
        """
        model = AssetsGetBodyStatusesResponse()
        if include_optional:
            return AssetsGetBodyStatusesResponse(
                body_status = [
                    kenar_api_client.models.assets_enum_option.assetsEnumOption(
                        display = '', 
                        slug = '', )
                    ]
            )
        else:
            return AssetsGetBodyStatusesResponse(
        )
        """

    def testAssetsGetBodyStatusesResponse(self):
        """Test AssetsGetBodyStatusesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
