# coding: utf-8

"""
    Kenar API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kenar_api_client.api.addons_api import AddonsApi


class TestAddonsApi(unittest.TestCase):
    """AddonsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AddonsApi()

    def tearDown(self) -> None:
        pass

    def test_addons_create_post_addon_v2(self) -> None:
        """Test case for addons_create_post_addon_v2

        Attach a new Addon to a post
        """
        pass

    def test_addons_create_user_addon_v2(self) -> None:
        """Test case for addons_create_user_addon_v2

        Attach a new Addon to a user
        """
        pass

    def test_addons_create_user_addon_v22(self) -> None:
        """Test case for addons_create_user_addon_v22

        Attach a new Addon to a user
        """
        pass

    def test_addons_delete_post_addon(self) -> None:
        """Test case for addons_delete_post_addon

        Delete an Addon from a post
        """
        pass

    def test_addons_delete_post_addon2(self) -> None:
        """Test case for addons_delete_post_addon2

        Delete an Addon from a post
        """
        pass

    def test_addons_delete_user_addon(self) -> None:
        """Test case for addons_delete_user_addon

        Delete an UserAddon
        """
        pass

    def test_addons_get_user_addons(self) -> None:
        """Test case for addons_get_user_addons

        Retrieve all UserAddons
        """
        pass

    def test_addons_get_user_addons2(self) -> None:
        """Test case for addons_get_user_addons2

        Retrieve all UserAddons
        """
        pass


if __name__ == '__main__':
    unittest.main()
