# coding: utf-8

"""
    divar_interface/open_platform/chatapi/chatapi.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kenar_api_client.models.chatapi_conversation_send_message_response import ChatapiConversationSendMessageResponse

class TestChatapiConversationSendMessageResponse(unittest.TestCase):
    """ChatapiConversationSendMessageResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChatapiConversationSendMessageResponse:
        """Test ChatapiConversationSendMessageResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChatapiConversationSendMessageResponse`
        """
        model = ChatapiConversationSendMessageResponse()
        if include_optional:
            return ChatapiConversationSendMessageResponse(
                status = 56,
                message = ''
            )
        else:
            return ChatapiConversationSendMessageResponse(
        )
        """

    def testChatapiConversationSendMessageResponse(self):
        """Test ChatapiConversationSendMessageResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
