# coding: utf-8

"""
    API کنار

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kenar_api_client.models.post_post_general_data import PostPostGeneralData

class TestPostPostGeneralData(unittest.TestCase):
    """PostPostGeneralData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostPostGeneralData:
        """Test PostPostGeneralData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostPostGeneralData`
        """
        model = PostPostGeneralData()
        if include_optional:
            return PostPostGeneralData(
                category_slug = 'apartment-sell',
                chat_enabled = True,
                city = 'tehran',
                description = 'I'm available only in chat.',
                district = 'abshar',
                hide_phone = True,
                images = [
                    ''
                    ],
                latitude = 35.7152,
                location_type = 'LOCATION_TYPE_EXACT',
                longitude = 51.4043,
                title = 'Temporary Residence for Rent in Tehran',
                video = kenar_api_client.models.post_general_data_post_video.PostGeneralDataPostVideo(
                    duration = '34', 
                    name = 'raw/4786eb10-eac6-4077-b622-78c1c42855c7.mp4', 
                    thumbnail_name = 'thumbnail/4786eb10-eac6-4077-b622-78c1c42855c7.jpg', )
            )
        else:
            return PostPostGeneralData(
                category_slug = 'apartment-sell',
                chat_enabled = True,
                city = 'tehran',
                description = 'I'm available only in chat.',
                hide_phone = True,
                images = [
                    ''
                    ],
                location_type = 'LOCATION_TYPE_EXACT',
                title = 'Temporary Residence for Rent in Tehran',
        )
        """

    def testPostPostGeneralData(self):
        """Test PostPostGeneralData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
