# coding: utf-8

"""
    divar_interface/open_platform/chatapi/chatapi.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kenar_api_client.models.chatapi_chat_button import ChatapiChatButton

class TestChatapiChatButton(unittest.TestCase):
    """ChatapiChatButton unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChatapiChatButton:
        """Test ChatapiChatButton
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChatapiChatButton`
        """
        model = ChatapiChatButton()
        if include_optional:
            return ChatapiChatButton(
                action = kenar_api_client.models.addons_action.addonsAction(
                    open_direct_link = '', 
                    open_server_link = kenar_api_client.models.addons_open_server_link.addonsOpenServerLink(
                        data = kenar_api_client.models.data.data(), ), 
                    get_dynamic_action = kenar_api_client.models.addons_get_dynamic_action.addonsGetDynamicAction(
                        data = kenar_api_client.models.data.data(), ), ),
                icon_name = '',
                caption = '',
                icon = 'KEYBOARD_ARROW_RIGHT'
            )
        else:
            return ChatapiChatButton(
        )
        """

    def testChatapiChatButton(self):
        """Test ChatapiChatButton"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
