# coding: utf-8

"""
    API کنار

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kenar_api_client.models.send_event_request_target_type import SendEventRequestTargetType

class TestSendEventRequestTargetType(unittest.TestCase):
    """SendEventRequestTargetType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSendEventRequestTargetType(self):
        """Test SendEventRequestTargetType"""
        # inst = SendEventRequestTargetType()

if __name__ == '__main__':
    unittest.main()
