# coding: utf-8

"""
    Kenar API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kenar_api_client.models.darvaze_get_car_ownership_status_response_status import DarvazeGetCarOwnershipStatusResponseStatus

class TestDarvazeGetCarOwnershipStatusResponseStatus(unittest.TestCase):
    """DarvazeGetCarOwnershipStatusResponseStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDarvazeGetCarOwnershipStatusResponseStatus(self):
        """Test DarvazeGetCarOwnershipStatusResponseStatus"""
        # inst = DarvazeGetCarOwnershipStatusResponseStatus()

if __name__ == '__main__':
    unittest.main()
