# coding: utf-8

"""
    API کنار

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kenar_api_client.api.addons_api import AddonsApi


class TestAddonsApi(unittest.TestCase):
    """AddonsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AddonsApi()

    def tearDown(self) -> None:
        pass

    def test_addons_create_business_addon(self) -> None:
        """Test case for addons_create_business_addon

        ایجاد افزونه کسب‌وکار
        """
        pass

    def test_addons_create_post_addon_v2(self) -> None:
        """Test case for addons_create_post_addon_v2

        ایجاد افزونه آگهی
        """
        pass

    def test_addons_create_user_addon_v2(self) -> None:
        """Test case for addons_create_user_addon_v2

        ایجاد افزونه کاربر
        """
        pass

    def test_addons_create_user_addon_v22(self) -> None:
        """Test case for addons_create_user_addon_v22

        ایجاد افزونه کاربر
        """
        pass

    def test_addons_delete_post_addon(self) -> None:
        """Test case for addons_delete_post_addon

        حذف افزونه آگهی
        """
        pass

    def test_addons_delete_post_addon2(self) -> None:
        """Test case for addons_delete_post_addon2

        حذف افزونه آگهی
        """
        pass

    def test_addons_delete_user_addon(self) -> None:
        """Test case for addons_delete_user_addon

        حذف افزونه کاربر
        """
        pass


if __name__ == '__main__':
    unittest.main()
