# coding: utf-8

"""
    divar_interface/open_platform/chatapi/chatapi.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kenar_api_client.models.addons_event_row import AddonsEventRow

class TestAddonsEventRow(unittest.TestCase):
    """AddonsEventRow unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddonsEventRow:
        """Test AddonsEventRow
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddonsEventRow`
        """
        model = AddonsEventRow()
        if include_optional:
            return AddonsEventRow(
                title = '',
                subtitle = '',
                label = '',
                image_id = '',
                has_divider = True,
                icon_name = 'KEYBOARD_ARROW_RIGHT'
            )
        else:
            return AddonsEventRow(
        )
        """

    def testAddonsEventRow(self):
        """Test AddonsEventRow"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
