# coding: utf-8

"""
    API کنار

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kenar_api_client.models.open_platformpost_services_fields import OpenPlatformpostServicesFields

class TestOpenPlatformpostServicesFields(unittest.TestCase):
    """OpenPlatformpostServicesFields unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OpenPlatformpostServicesFields:
        """Test OpenPlatformpostServicesFields
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OpenPlatformpostServicesFields`
        """
        model = OpenPlatformpostServicesFields()
        if include_optional:
            return OpenPlatformpostServicesFields(
                category = 'CATEGORY_CAR_AND_MOTOR',
                expertise_ids = ["1","2"],
                work_hours_end = 18,
                work_hours_start = 9,
                work_on_holidays = True,
                works_24_7 = False
            )
        else:
            return OpenPlatformpostServicesFields(
                category = 'CATEGORY_CAR_AND_MOTOR',
                expertise_ids = ["1","2"],
                work_hours_end = 18,
                work_hours_start = 9,
                work_on_holidays = True,
                works_24_7 = False,
        )
        """

    def testOpenPlatformpostServicesFields(self):
        """Test OpenPlatformpostServicesFields"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
