# coding: utf-8

"""
    Kenar API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AddonsWidgetColor(str, Enum):
    """
    AddonsWidgetColor
    """

    """
    allowed enum values
    """
    WARNING_SECONDARY = 'WARNING_SECONDARY'
    WARNING_PRIMARY = 'WARNING_PRIMARY'
    ERROR_PRIMARY = 'ERROR_PRIMARY'
    SUCCESS_PRIMARY = 'SUCCESS_PRIMARY'
    SUCCESS_SECONDARY = 'SUCCESS_SECONDARY'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AddonsWidgetColor from a JSON string"""
        return cls(json.loads(json_str))


