# coding: utf-8

"""
    divar_interface/open_platform/chatapi/chatapi.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from kenar_api_client.models.addons_get_dynamic_action import AddonsGetDynamicAction
from kenar_api_client.models.addons_open_server_link import AddonsOpenServerLink
from typing import Optional, Set
from typing_extensions import Self

class AddonsAction(BaseModel):
    """
    AddonsAction
    """ # noqa: E501
    open_direct_link: Optional[StrictStr] = None
    open_server_link: Optional[AddonsOpenServerLink] = None
    get_dynamic_action: Optional[AddonsGetDynamicAction] = None
    __properties: ClassVar[List[str]] = ["open_direct_link", "open_server_link", "get_dynamic_action"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AddonsAction from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of open_server_link
        if self.open_server_link:
            _dict['open_server_link'] = self.open_server_link.to_dict()
        # override the default output from pydantic by calling `to_dict()` of get_dynamic_action
        if self.get_dynamic_action:
            _dict['get_dynamic_action'] = self.get_dynamic_action.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AddonsAction from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "open_direct_link": obj.get("open_direct_link"),
            "open_server_link": AddonsOpenServerLink.from_dict(obj["open_server_link"]) if obj.get("open_server_link") is not None else None,
            "get_dynamic_action": AddonsGetDynamicAction.from_dict(obj["get_dynamic_action"]) if obj.get("get_dynamic_action") is not None else None
        })
        return _obj


