# coding: utf-8

"""
    API کنار

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AddonSemanticCarVerificationStage(str, Enum):
    """
    AddonSemanticCarVerificationStage
    """

    """
    allowed enum values
    """
    CARVERIFICATIONSTAGE_NOT_STARTED = 'CARVERIFICATIONSTAGE_NOT_STARTED'
    CARVERIFICATIONSTAGE_SHAHKAR = 'CARVERIFICATIONSTAGE_SHAHKAR'
    CAR_CARD_VERIFICATION = 'CAR_CARD_VERIFICATION'
    CAR_MODEL_VERIFICATION = 'CAR_MODEL_VERIFICATION'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AddonSemanticCarVerificationStage from a JSON string"""
        return cls(json.loads(json_str))


