# coding: utf-8

"""
    divar_interface/open_platform/chatapi/chatapi.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AddonsAddonSemanticStatus(str, Enum):
    """
    AddonsAddonSemanticStatus
    """

    """
    allowed enum values
    """
    SUCCEEDED = 'SUCCEEDED'
    FAILED = 'FAILED'
    EXPIRED = 'EXPIRED'
    PENDING = 'PENDING'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AddonsAddonSemanticStatus from a JSON string"""
        return cls(json.loads(json_str))


