# coding: utf-8

"""
    divar_interface/open_platform/chatapi/chatapi.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AppsServiceType(str, Enum):
    """
    AppsServiceType
    """

    """
    allowed enum values
    """
    FUNC_CLICK_AND_COLLECT = 'FUNC_CLICK_AND_COLLECT'
    FUNC_DELIVERY = 'FUNC_DELIVERY'
    FUNC_SECURE_PAYMENT = 'FUNC_SECURE_PAYMENT'
    LEAD_GEN_PURE = 'LEAD_GEN_PURE'
    LEAD_GEN_LOAN = 'LEAD_GEN_LOAN'
    REPORT_INSPECTION = 'REPORT_INSPECTION'
    REPORT_PRICE_EVALUATION = 'REPORT_PRICE_EVALUATION'
    REPORT_VERIFICATION = 'REPORT_VERIFICATION'
    FUNC_CONTRACT = 'FUNC_CONTRACT'
    FUNC_FINANCING = 'FUNC_FINANCING'
    USER_FACE_ID_VERIFICATION = 'USER_FACE_ID_VERIFICATION'
    POST_VERIFICATION = 'POST_VERIFICATION'
    INTERNAL = 'INTERNAL'
    USER_BACKGROUND_VERIFICATION = 'USER_BACKGROUND_VERIFICATION'
    USER_BUSINESS_VERIFICATION = 'USER_BUSINESS_VERIFICATION'
    CHARITY = 'CHARITY'
    SECURE_PAYMENT_POST_PROMOTION = 'SECURE_PAYMENT_POST_PROMOTION'
    PHOTOGRAPHY = 'PHOTOGRAPHY'
    DOWNLOADABLE_CONTENT_GENERATION = 'DOWNLOADABLE_CONTENT_GENERATION'
    REPORT_INSPECTION_CHAT = 'REPORT_INSPECTION_CHAT'
    ADDITIONAL_INFORMATION = 'ADDITIONAL_INFORMATION'
    ACCOUNTING = 'ACCOUNTING'
    ASSISTANT = 'ASSISTANT'
    ADVERTISEMENT = 'ADVERTISEMENT'
    CONTRACT_POST = 'CONTRACT_POST'
    SITE_BUILDER = 'SITE_BUILDER'
    FORM_BUILDER = 'FORM_BUILDER'
    AUCTION = 'AUCTION'
    POST_DETAIL_ENHANCER = 'POST_DETAIL_ENHANCER'
    POST_REORDER = 'POST_REORDER'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AppsServiceType from a JSON string"""
        return cls(json.loads(json_str))


