# coding: utf-8

"""
    Kenar API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class HomePresellFieldsDeliveryMonth(str, Enum):
    """
    ماه تحویل (تقویم شمسی)
    """

    """
    allowed enum values
    """
    DELIVERY_MONTH_FARVARDIN = 'DELIVERY_MONTH_FARVARDIN'
    DELIVERY_MONTH_ORDIBEHESHT = 'DELIVERY_MONTH_ORDIBEHESHT'
    DELIVERY_MONTH_KHORDAD = 'DELIVERY_MONTH_KHORDAD'
    DELIVERY_MONTH_TIR = 'DELIVERY_MONTH_TIR'
    DELIVERY_MONTH_MORDAD = 'DELIVERY_MONTH_MORDAD'
    DELIVERY_MONTH_SHAHRIVAR = 'DELIVERY_MONTH_SHAHRIVAR'
    DELIVERY_MONTH_MEHR = 'DELIVERY_MONTH_MEHR'
    DELIVERY_MONTH_ABAN = 'DELIVERY_MONTH_ABAN'
    DELIVERY_MONTH_AZAR = 'DELIVERY_MONTH_AZAR'
    DELIVERY_MONTH_DEY = 'DELIVERY_MONTH_DEY'
    DELIVERY_MONTH_BAHMAN = 'DELIVERY_MONTH_BAHMAN'
    DELIVERY_MONTH_ESFAND = 'DELIVERY_MONTH_ESFAND'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of HomePresellFieldsDeliveryMonth from a JSON string"""
        return cls(json.loads(json_str))


