# coding: utf-8

"""
    Kenar API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class HomePresellFieldsDeliveryYear(str, Enum):
    """
    Delivery year (Persian/Shamsi calendar)
    """

    """
    allowed enum values
    """
    DELIVERY_YEAR_1404 = 'DELIVERY_YEAR_1404'
    DELIVERY_YEAR_1405 = 'DELIVERY_YEAR_1405'
    DELIVERY_YEAR_1406 = 'DELIVERY_YEAR_1406'
    DELIVERY_YEAR_1407 = 'DELIVERY_YEAR_1407'
    DELIVERY_YEAR_1408 = 'DELIVERY_YEAR_1408'
    DELIVERY_YEAR_1409 = 'DELIVERY_YEAR_1409'
    DELIVERY_YEAR_1410 = 'DELIVERY_YEAR_1410'
    DELIVERY_YEAR_1411 = 'DELIVERY_YEAR_1411'
    DELIVERY_YEAR_1412 = 'DELIVERY_YEAR_1412'
    DELIVERY_YEAR_1413 = 'DELIVERY_YEAR_1413'
    DELIVERY_YEAR_1414 = 'DELIVERY_YEAR_1414'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of HomePresellFieldsDeliveryYear from a JSON string"""
        return cls(json.loads(json_str))


