# coding: utf-8

"""
    API کنار

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class OpenPlatformpostPostState(str, Enum):
    """
    OpenPlatformpostPostState
    """

    """
    allowed enum values
    """
    POST_STATE_IN_PUBLISH_QUEUE = 'POST_STATE_IN_PUBLISH_QUEUE'
    POST_STATE_PUBLISHED = 'POST_STATE_PUBLISHED'
    POST_STATE_WAITING_FOR_EDIT = 'POST_STATE_WAITING_FOR_EDIT'
    POST_STATE_WAITING_FOR_PAYMENT = 'POST_STATE_WAITING_FOR_PAYMENT'
    POST_STATE_WAITING_FOR_REVIEW = 'POST_STATE_WAITING_FOR_REVIEW'
    POST_STATE_PUBLISHED_AND_EDIT_REJECTED = 'POST_STATE_PUBLISHED_AND_EDIT_REJECTED'
    POST_STATE_REJECTED = 'POST_STATE_REJECTED'
    POST_STATE_DELETED = 'POST_STATE_DELETED'
    POST_STATE_RETIRED = 'POST_STATE_RETIRED'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OpenPlatformpostPostState from a JSON string"""
        return cls(json.loads(json_str))


