# coding: utf-8

"""
    API کنار

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from kenar_api_client.models.services_fields_category import ServicesFieldsCategory
from typing import Optional, Set
from typing_extensions import Self

class OpenPlatformpostServicesFields(BaseModel):
    """
    OpenPlatformpostServicesFields
    """ # noqa: E501
    category: ServicesFieldsCategory
    expertise_ids: List[StrictStr] = Field(description="فهرست شناسه‌های تخصص")
    work_hours_end: StrictInt = Field(description="ساعت پایان کار به فرمت 24 ساعته (مثلاً 18 برای 18:00). فقط در صورتی اعمال می‌شود که `works_24_7` false باشد.")
    work_hours_start: StrictInt = Field(description="ساعت شروع کار به فرمت 24 ساعته (مثلاً 9 برای 9:00). فقط در صورتی اعمال می‌شود که `works_24_7` false باشد.")
    work_on_holidays: StrictBool = Field(description="آیا ارائه‌دهنده سرویس در تعطیلات کار می‌کند")
    works_24_7: StrictBool = Field(description="آیا ارائه‌دهنده سرویس به صورت 24/7 در دسترس است. اگر true باشد، `work_hours_start` و `work_hours_end` نادیده گرفته می‌شوند.")
    __properties: ClassVar[List[str]] = ["category", "expertise_ids", "work_hours_end", "work_hours_start", "work_on_holidays", "works_24_7"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OpenPlatformpostServicesFields from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OpenPlatformpostServicesFields from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "category": obj.get("category"),
            "expertise_ids": obj.get("expertise_ids"),
            "work_hours_end": obj.get("work_hours_end"),
            "work_hours_start": obj.get("work_hours_start"),
            "work_on_holidays": obj.get("work_on_holidays"),
            "works_24_7": obj.get("works_24_7")
        })
        return _obj


