# coding: utf-8

"""
    API کنار

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PostCustomizedButtonType(str, Enum):
    """
    نوع دکمه اختصاصی که هدف و رفتار آن را تعیین می‌کند. ویژگی‌هایی مانند عنوان دکمه بر اساس نوع آن تعیین می‌شوند.  انواع موجود: - `ACCOMMODATION_BOOKING`: برای رزرو اقامتگاه - `EXTERNAL_PRODUCT_STORE`: برای مشاهده و خرید محصولات در فروشگاه‌های آنلاین - `RESUME_SUBMISSION`: برای ارسال رزومه 
    """

    """
    allowed enum values
    """
    ACCOMMODATION_BOOKING = 'ACCOMMODATION_BOOKING'
    EXTERNAL_PRODUCT_STORE = 'EXTERNAL_PRODUCT_STORE'
    RESUME_SUBMISSION = 'RESUME_SUBMISSION'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PostCustomizedButtonType from a JSON string"""
        return cls(json.loads(json_str))


