# coding: utf-8

"""
    API کنار

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PostRoomsCount(str, Enum):
    """
    تعداد اتاق‌های اقامتگاه
    """

    """
    allowed enum values
    """
    ROOMS_COUNT_0 = 'ROOMS_COUNT_0'
    ROOMS_COUNT_1 = 'ROOMS_COUNT_1'
    ROOMS_COUNT_2 = 'ROOMS_COUNT_2'
    ROOMS_COUNT_3 = 'ROOMS_COUNT_3'
    ROOMS_COUNT_4 = 'ROOMS_COUNT_4'
    ROOMS_COUNT_5_OR_MORE = 'ROOMS_COUNT_5_OR_MORE'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PostRoomsCount from a JSON string"""
        return cls(json.loads(json_str))


