# coding: utf-8

"""
    API کنار

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from kenar_api_client.models.open_platformpost_post_state import OpenPlatformpostPostState
from kenar_api_client.models.post_get_user_post_response_business_data import PostGetUserPostResponseBusinessData
from kenar_api_client.models.post_post_general_data import PostPostGeneralData
from typing import Optional, Set
from typing_extensions import Self

class PostGetUserPostResponse(BaseModel):
    """
    PostGetUserPostResponse
    """ # noqa: E501
    business_data: Optional[PostGetUserPostResponseBusinessData] = None
    category_data: Optional[Dict[str, Any]] = None
    general_data: Optional[PostPostGeneralData] = None
    reject_reason: Optional[StrictStr] = None
    state: Optional[OpenPlatformpostPostState] = None
    __properties: ClassVar[List[str]] = ["business_data", "category_data", "general_data", "reject_reason", "state"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PostGetUserPostResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of business_data
        if self.business_data:
            _dict['business_data'] = self.business_data.to_dict()
        # override the default output from pydantic by calling `to_dict()` of general_data
        if self.general_data:
            _dict['general_data'] = self.general_data.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PostGetUserPostResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "business_data": PostGetUserPostResponseBusinessData.from_dict(obj["business_data"]) if obj.get("business_data") is not None else None,
            "category_data": obj.get("category_data"),
            "general_data": PostPostGeneralData.from_dict(obj["general_data"]) if obj.get("general_data") is not None else None,
            "reject_reason": obj.get("reject_reason"),
            "state": obj.get("state")
        })
        return _obj


