# coding: utf-8

"""
    Kenar API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from kenar_api_client.models.post_temporary_residence_fields import PostTemporaryResidenceFields
from typing import Optional, Set
from typing_extensions import Self

class PostSubmitPostRequest(BaseModel):
    """
    PostSubmitPostRequest
    """ # noqa: E501
    chat_enabled: Optional[StrictBool] = Field(default=None, description="Whether to enable chat")
    city: Optional[StrictStr] = Field(default=None, description="City of the post")
    description: Optional[StrictStr] = Field(default=None, description="Description of the post")
    district: Optional[StrictStr] = Field(default=None, description="District of the post")
    hide_phone: Optional[StrictBool] = Field(default=None, description="Whether to hide the phone number from demand users")
    images: Optional[List[StrictStr]] = None
    latitude: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Latitude of the post")
    longitude: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Longitude of the post")
    temporary_residence: Optional[PostTemporaryResidenceFields] = None
    title: Optional[StrictStr] = Field(default=None, description="Title of the post")
    __properties: ClassVar[List[str]] = ["chat_enabled", "city", "description", "district", "hide_phone", "images", "latitude", "longitude", "temporary_residence", "title"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PostSubmitPostRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of temporary_residence
        if self.temporary_residence:
            _dict['temporary_residence'] = self.temporary_residence.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PostSubmitPostRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "chat_enabled": obj.get("chat_enabled"),
            "city": obj.get("city"),
            "description": obj.get("description"),
            "district": obj.get("district"),
            "hide_phone": obj.get("hide_phone"),
            "images": obj.get("images"),
            "latitude": obj.get("latitude"),
            "longitude": obj.get("longitude"),
            "temporary_residence": PostTemporaryResidenceFields.from_dict(obj["temporary_residence"]) if obj.get("temporary_residence") is not None else None,
            "title": obj.get("title")
        })
        return _obj


